name: Build PyQt5 EXE

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0
  workflow_dispatch:  # Allow manual runs

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Adjust based on your project

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller FlatCAM.py --onefile --windowed --name=MyApp

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-exe
          path: dist/MyApp.exe

      - name: Upload to GitHub Releases
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/MyApp.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
